#!/bin/bash

NUC_WMI_CLI_VERSION="$(dpkg-query --show --showformat '${VERSION}\n' python3-asus-nuc-wmi 2>/dev/null)"

function regression_test()
{
  set -x

  lsb_release -a
  uname -a

  time asus_nuc_wmi-query_led_group_attribute --debug
  time asus_nuc_wmi-update_led_group_attribute 'Power State Indicator' 'Normally OFF, ON when active' 'Blue' 'Solid' '1.0Hz' '100' 'Black' 'Solid' '1.0Hz' '0'
  time asus_nuc_wmi-query_led_group_attribute --debug
  time asus_nuc_wmi-update_led_group_attribute 'Power State Indicator' 'Normally OFF, ON when active' 'Amber' 'Strobing' '0.1Hz' '50' 'Black' 'Solid' '1.0Hz' '0'
  time asus_nuc_wmi-query_led_group_attribute --debug
  time asus_nuc_wmi-update_led_group_attribute 'HDD Activity Indicator' 'Normally OFF, ON when active' 'Blue' 'Strobing' '0.1Hz' '100' 'Black' 'Solid' '1.0Hz' '0'
  time asus_nuc_wmi-query_led_group_attribute --debug
  time asus_nuc_wmi-update_led_group_attribute 'HDD Activity Indicator' 'Normally ON, OFF when active' 'Amber' 'Strobing' '0.1Hz' '50' 'Black' 'Solid' '1.0Hz' '0'
  time asus_nuc_wmi-query_led_group_attribute --debug
  time asus_nuc_wmi-update_led_group_attribute 'Software Indicator' 'Normally OFF, ON when active' 'Blue' 'Solid' '1.0Hz' '100' 'Black' 'Solid' '1.0Hz' '0'
  time asus_nuc_wmi-query_led_group_attribute --debug
  time asus_nuc_wmi-update_led_group_attribute 'Software Indicator' 'Normally OFF, ON when active' 'Amber' 'Strobing' '0.1Hz' '50' 'Black' 'Solid' '1.0Hz' '0'
  time asus_nuc_wmi-query_led_group_attribute --debug

  set +x
}

{ time regression_test; } > "nuc_14_cli_${NUC_WMI_CLI_VERSION}.log" 2>&1
